// login
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

// signup
export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"

// getUserPhone
export const GET_USER_PHONE_REQUEST = "GET_USER_PHONE_REQUEST"
export const GET_USER_PHONE_SUCCESS = "GET_USER_PHONE_SUCCESS"
export const GET_USER_PHONE_ERROR = "GET_USER_PHONE_ERROR"

// getVerificationCode
export const GET_VERIFICATION_CODE_REQUEST = "GET_VERIFICATION_CODE_REQUEST"
export const GET_VERIFICATION_CODE_SUCCESS = "GET_VERIFICATION_CODE_SUCCESS"
export const GET_VERIFICATION_CODE_ERROR = "GET_VERIFICATION_CODE_ERROR"

// sendVerificationCode
export const SEND_VERIFICATION_CODE_REQUEST = "SEND_VERIFICATION_CODE_REQUEST"
export const SEND_VERIFICATION_CODE_SUCCESS = "SEND_VERIFICATION_CODE_SUCCESS"
export const SEND_VERIFICATION_CODE_ERROR = "SEND_VERIFICATION_CODE_ERROR"

// logout
export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"

// checkToken
export const CHECK_TOKEN_REQUEST = "CHECK_TOKEN_REQUEST"
export const CHECK_TOKEN_SUCCESS = "CHECK_TOKEN_SUCCESS"
export const CHECK_TOKEN_ERROR = "CHECK_TOKEN_ERROR"